// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: mnemovela_v1.proto

package mnemovelav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mneme_CommitMemory_FullMethodName           = "/mnemovela.v1.Mneme/CommitMemory"
	Mneme_AddEpisode_FullMethodName             = "/mnemovela.v1.Mneme/AddEpisode"
	Mneme_AddFact_FullMethodName                = "/mnemovela.v1.Mneme/AddFact"
	Mneme_InvalidateFact_FullMethodName         = "/mnemovela.v1.Mneme/InvalidateFact"
	Mneme_UpsertSubject_FullMethodName          = "/mnemovela.v1.Mneme/UpsertSubject"
	Mneme_UpsertEntity_FullMethodName           = "/mnemovela.v1.Mneme/UpsertEntity"
	Mneme_SearchMemory_FullMethodName           = "/mnemovela.v1.Mneme/SearchMemory"
	Mneme_QueryMemories_FullMethodName          = "/mnemovela.v1.Mneme/QueryMemories"
	Mneme_QueryFacts_FullMethodName             = "/mnemovela.v1.Mneme/QueryFacts"
	Mneme_ResolveEntity_FullMethodName          = "/mnemovela.v1.Mneme/ResolveEntity"
	Mneme_ResolveEntityExplained_FullMethodName = "/mnemovela.v1.Mneme/ResolveEntityExplained"
	Mneme_ExtractEpisode_FullMethodName         = "/mnemovela.v1.Mneme/ExtractEpisode"
	Mneme_CreateBranch_FullMethodName           = "/mnemovela.v1.Mneme/CreateBranch"
	Mneme_MergeBranch_FullMethodName            = "/mnemovela.v1.Mneme/MergeBranch"
	Mneme_ListBranches_FullMethodName           = "/mnemovela.v1.Mneme/ListBranches"
	Mneme_SetRetentionState_FullMethodName      = "/mnemovela.v1.Mneme/SetRetentionState"
	Mneme_VerifyCommitIndex_FullMethodName      = "/mnemovela.v1.Mneme/VerifyCommitIndex"
)

// MnemeClient is the client API for Mneme service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MnemeClient interface {
	// --- typed writes ---
	CommitMemory(ctx context.Context, in *CommitMemoryRequest, opts ...grpc.CallOption) (*CommitMemoryResponse, error)
	AddEpisode(ctx context.Context, in *AddEpisodeRequest, opts ...grpc.CallOption) (*AddEpisodeResponse, error)
	AddFact(ctx context.Context, in *AddFactRequest, opts ...grpc.CallOption) (*AddFactResponse, error)
	InvalidateFact(ctx context.Context, in *InvalidateFactRequest, opts ...grpc.CallOption) (*InvalidateFactResponse, error)
	UpsertSubject(ctx context.Context, in *UpsertSubjectRequest, opts ...grpc.CallOption) (*UpsertSubjectResponse, error)
	UpsertEntity(ctx context.Context, in *UpsertEntityRequest, opts ...grpc.CallOption) (*UpsertEntityResponse, error)
	// --- queries ---
	SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error)
	QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error)
	QueryFacts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error)
	// --- resolution ---
	ResolveEntity(ctx context.Context, in *ResolveEntityRequest, opts ...grpc.CallOption) (*ResolveEntityResponse, error)
	ResolveEntityExplained(ctx context.Context, in *ResolveEntityExplainedRequest, opts ...grpc.CallOption) (*ResolveEntityExplainedResponse, error)
	// --- extraction ---
	ExtractEpisode(ctx context.Context, in *ExtractEpisodeRequest, opts ...grpc.CallOption) (*ExtractEpisodeResponse, error)
	// --- branching ---
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error)
	// --- maintenance ---
	SetRetentionState(ctx context.Context, in *SetRetentionStateRequest, opts ...grpc.CallOption) (*SetRetentionStateResponse, error)
	VerifyCommitIndex(ctx context.Context, in *VerifyCommitIndexRequest, opts ...grpc.CallOption) (*VerifyCommitIndexResponse, error)
}

type mnemeClient struct {
	cc grpc.ClientConnInterface
}

func NewMnemeClient(cc grpc.ClientConnInterface) MnemeClient {
	return &mnemeClient{cc}
}

func (c *mnemeClient) CommitMemory(ctx context.Context, in *CommitMemoryRequest, opts ...grpc.CallOption) (*CommitMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMemoryResponse)
	err := c.cc.Invoke(ctx, Mneme_CommitMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) AddEpisode(ctx context.Context, in *AddEpisodeRequest, opts ...grpc.CallOption) (*AddEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEpisodeResponse)
	err := c.cc.Invoke(ctx, Mneme_AddEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) AddFact(ctx context.Context, in *AddFactRequest, opts ...grpc.CallOption) (*AddFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFactResponse)
	err := c.cc.Invoke(ctx, Mneme_AddFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) InvalidateFact(ctx context.Context, in *InvalidateFactRequest, opts ...grpc.CallOption) (*InvalidateFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateFactResponse)
	err := c.cc.Invoke(ctx, Mneme_InvalidateFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) UpsertSubject(ctx context.Context, in *UpsertSubjectRequest, opts ...grpc.CallOption) (*UpsertSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSubjectResponse)
	err := c.cc.Invoke(ctx, Mneme_UpsertSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) UpsertEntity(ctx context.Context, in *UpsertEntityRequest, opts ...grpc.CallOption) (*UpsertEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEntityResponse)
	err := c.cc.Invoke(ctx, Mneme_UpsertEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMemoryResponse)
	err := c.cc.Invoke(ctx, Mneme_SearchMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMemoriesResponse)
	err := c.cc.Invoke(ctx, Mneme_QueryMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) QueryFacts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsResponse)
	err := c.cc.Invoke(ctx, Mneme_QueryFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) ResolveEntity(ctx context.Context, in *ResolveEntityRequest, opts ...grpc.CallOption) (*ResolveEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEntityResponse)
	err := c.cc.Invoke(ctx, Mneme_ResolveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) ResolveEntityExplained(ctx context.Context, in *ResolveEntityExplainedRequest, opts ...grpc.CallOption) (*ResolveEntityExplainedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEntityExplainedResponse)
	err := c.cc.Invoke(ctx, Mneme_ResolveEntityExplained_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) ExtractEpisode(ctx context.Context, in *ExtractEpisodeRequest, opts ...grpc.CallOption) (*ExtractEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractEpisodeResponse)
	err := c.cc.Invoke(ctx, Mneme_ExtractEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, Mneme_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeBranchResponse)
	err := c.cc.Invoke(ctx, Mneme_MergeBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, Mneme_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) SetRetentionState(ctx context.Context, in *SetRetentionStateRequest, opts ...grpc.CallOption) (*SetRetentionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRetentionStateResponse)
	err := c.cc.Invoke(ctx, Mneme_SetRetentionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemeClient) VerifyCommitIndex(ctx context.Context, in *VerifyCommitIndexRequest, opts ...grpc.CallOption) (*VerifyCommitIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCommitIndexResponse)
	err := c.cc.Invoke(ctx, Mneme_VerifyCommitIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MnemeServer is the server API for Mneme service.
// All implementations must embed UnimplementedMnemeServer
// for forward compatibility.
type MnemeServer interface {
	// --- typed writes ---
	CommitMemory(context.Context, *CommitMemoryRequest) (*CommitMemoryResponse, error)
	AddEpisode(context.Context, *AddEpisodeRequest) (*AddEpisodeResponse, error)
	AddFact(context.Context, *AddFactRequest) (*AddFactResponse, error)
	InvalidateFact(context.Context, *InvalidateFactRequest) (*InvalidateFactResponse, error)
	UpsertSubject(context.Context, *UpsertSubjectRequest) (*UpsertSubjectResponse, error)
	UpsertEntity(context.Context, *UpsertEntityRequest) (*UpsertEntityResponse, error)
	// --- queries ---
	SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error)
	QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error)
	QueryFacts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error)
	// --- resolution ---
	ResolveEntity(context.Context, *ResolveEntityRequest) (*ResolveEntityResponse, error)
	ResolveEntityExplained(context.Context, *ResolveEntityExplainedRequest) (*ResolveEntityExplainedResponse, error)
	// --- extraction ---
	ExtractEpisode(context.Context, *ExtractEpisodeRequest) (*ExtractEpisodeResponse, error)
	// --- branching ---
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error)
	// --- maintenance ---
	SetRetentionState(context.Context, *SetRetentionStateRequest) (*SetRetentionStateResponse, error)
	VerifyCommitIndex(context.Context, *VerifyCommitIndexRequest) (*VerifyCommitIndexResponse, error)
	mustEmbedUnimplementedMnemeServer()
}

// UnimplementedMnemeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMnemeServer struct{}

func (UnimplementedMnemeServer) CommitMemory(context.Context, *CommitMemoryRequest) (*CommitMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitMemory not implemented")
}
func (UnimplementedMnemeServer) AddEpisode(context.Context, *AddEpisodeRequest) (*AddEpisodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEpisode not implemented")
}
func (UnimplementedMnemeServer) AddFact(context.Context, *AddFactRequest) (*AddFactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFact not implemented")
}
func (UnimplementedMnemeServer) InvalidateFact(context.Context, *InvalidateFactRequest) (*InvalidateFactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidateFact not implemented")
}
func (UnimplementedMnemeServer) UpsertSubject(context.Context, *UpsertSubjectRequest) (*UpsertSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertSubject not implemented")
}
func (UnimplementedMnemeServer) UpsertEntity(context.Context, *UpsertEntityRequest) (*UpsertEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEntity not implemented")
}
func (UnimplementedMnemeServer) SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMemory not implemented")
}
func (UnimplementedMnemeServer) QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMemories not implemented")
}
func (UnimplementedMnemeServer) QueryFacts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryFacts not implemented")
}
func (UnimplementedMnemeServer) ResolveEntity(context.Context, *ResolveEntityRequest) (*ResolveEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEntity not implemented")
}
func (UnimplementedMnemeServer) ResolveEntityExplained(context.Context, *ResolveEntityExplainedRequest) (*ResolveEntityExplainedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEntityExplained not implemented")
}
func (UnimplementedMnemeServer) ExtractEpisode(context.Context, *ExtractEpisodeRequest) (*ExtractEpisodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractEpisode not implemented")
}
func (UnimplementedMnemeServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedMnemeServer) MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeBranch not implemented")
}
func (UnimplementedMnemeServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedMnemeServer) SetRetentionState(context.Context, *SetRetentionStateRequest) (*SetRetentionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRetentionState not implemented")
}
func (UnimplementedMnemeServer) VerifyCommitIndex(context.Context, *VerifyCommitIndexRequest) (*VerifyCommitIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCommitIndex not implemented")
}
func (UnimplementedMnemeServer) mustEmbedUnimplementedMnemeServer() {}
func (UnimplementedMnemeServer) testEmbeddedByValue()               {}

// UnsafeMnemeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MnemeServer will
// result in compilation errors.
type UnsafeMnemeServer interface {
	mustEmbedUnimplementedMnemeServer()
}

func RegisterMnemeServer(s grpc.ServiceRegistrar, srv MnemeServer) {
	// If the following call panics, it indicates UnimplementedMnemeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mneme_ServiceDesc, srv)
}

func _Mneme_CommitMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).CommitMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_CommitMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).CommitMemory(ctx, req.(*CommitMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_AddEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).AddEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_AddEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).AddEpisode(ctx, req.(*AddEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_AddFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).AddFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_AddFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).AddFact(ctx, req.(*AddFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_InvalidateFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).InvalidateFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_InvalidateFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).InvalidateFact(ctx, req.(*InvalidateFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_UpsertSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).UpsertSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_UpsertSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).UpsertSubject(ctx, req.(*UpsertSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_UpsertEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).UpsertEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_UpsertEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).UpsertEntity(ctx, req.(*UpsertEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_SearchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).SearchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_SearchMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).SearchMemory(ctx, req.(*SearchMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_QueryMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).QueryMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_QueryMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).QueryMemories(ctx, req.(*QueryMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_QueryFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).QueryFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_QueryFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).QueryFacts(ctx, req.(*QueryFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_ResolveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).ResolveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_ResolveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).ResolveEntity(ctx, req.(*ResolveEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_ResolveEntityExplained_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEntityExplainedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).ResolveEntityExplained(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_ResolveEntityExplained_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).ResolveEntityExplained(ctx, req.(*ResolveEntityExplainedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_ExtractEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).ExtractEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_ExtractEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).ExtractEpisode(ctx, req.(*ExtractEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_MergeBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).MergeBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_MergeBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).MergeBranch(ctx, req.(*MergeBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_SetRetentionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRetentionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).SetRetentionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_SetRetentionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).SetRetentionState(ctx, req.(*SetRetentionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mneme_VerifyCommitIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCommitIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemeServer).VerifyCommitIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mneme_VerifyCommitIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemeServer).VerifyCommitIndex(ctx, req.(*VerifyCommitIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mneme_ServiceDesc is the grpc.ServiceDesc for Mneme service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mneme_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mnemovela.v1.Mneme",
	HandlerType: (*MnemeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitMemory",
			Handler:    _Mneme_CommitMemory_Handler,
		},
		{
			MethodName: "AddEpisode",
			Handler:    _Mneme_AddEpisode_Handler,
		},
		{
			MethodName: "AddFact",
			Handler:    _Mneme_AddFact_Handler,
		},
		{
			MethodName: "InvalidateFact",
			Handler:    _Mneme_InvalidateFact_Handler,
		},
		{
			MethodName: "UpsertSubject",
			Handler:    _Mneme_UpsertSubject_Handler,
		},
		{
			MethodName: "UpsertEntity",
			Handler:    _Mneme_UpsertEntity_Handler,
		},
		{
			MethodName: "SearchMemory",
			Handler:    _Mneme_SearchMemory_Handler,
		},
		{
			MethodName: "QueryMemories",
			Handler:    _Mneme_QueryMemories_Handler,
		},
		{
			MethodName: "QueryFacts",
			Handler:    _Mneme_QueryFacts_Handler,
		},
		{
			MethodName: "ResolveEntity",
			Handler:    _Mneme_ResolveEntity_Handler,
		},
		{
			MethodName: "ResolveEntityExplained",
			Handler:    _Mneme_ResolveEntityExplained_Handler,
		},
		{
			MethodName: "ExtractEpisode",
			Handler:    _Mneme_ExtractEpisode_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _Mneme_CreateBranch_Handler,
		},
		{
			MethodName: "MergeBranch",
			Handler:    _Mneme_MergeBranch_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _Mneme_ListBranches_Handler,
		},
		{
			MethodName: "SetRetentionState",
			Handler:    _Mneme_SetRetentionState_Handler,
		},
		{
			MethodName: "VerifyCommitIndex",
			Handler:    _Mneme_VerifyCommitIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mnemovela_v1.proto",
}
