// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: mnemovela_v1.proto

package mnemovelav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mnemovela_CommitMemory_FullMethodName           = "/mnemovela.v1.Mnemovela/CommitMemory"
	Mnemovela_AddEpisode_FullMethodName             = "/mnemovela.v1.Mnemovela/AddEpisode"
	Mnemovela_AddFact_FullMethodName                = "/mnemovela.v1.Mnemovela/AddFact"
	Mnemovela_InvalidateFact_FullMethodName         = "/mnemovela.v1.Mnemovela/InvalidateFact"
	Mnemovela_UpsertSubject_FullMethodName          = "/mnemovela.v1.Mnemovela/UpsertSubject"
	Mnemovela_UpsertEntity_FullMethodName           = "/mnemovela.v1.Mnemovela/UpsertEntity"
	Mnemovela_SearchMemory_FullMethodName           = "/mnemovela.v1.Mnemovela/SearchMemory"
	Mnemovela_QueryMemories_FullMethodName          = "/mnemovela.v1.Mnemovela/QueryMemories"
	Mnemovela_QueryFacts_FullMethodName             = "/mnemovela.v1.Mnemovela/QueryFacts"
	Mnemovela_ResolveEntity_FullMethodName          = "/mnemovela.v1.Mnemovela/ResolveEntity"
	Mnemovela_ResolveEntityExplained_FullMethodName = "/mnemovela.v1.Mnemovela/ResolveEntityExplained"
	Mnemovela_ExtractEpisode_FullMethodName         = "/mnemovela.v1.Mnemovela/ExtractEpisode"
	Mnemovela_CreateBranch_FullMethodName           = "/mnemovela.v1.Mnemovela/CreateBranch"
	Mnemovela_MergeBranch_FullMethodName            = "/mnemovela.v1.Mnemovela/MergeBranch"
	Mnemovela_ListBranches_FullMethodName           = "/mnemovela.v1.Mnemovela/ListBranches"
	Mnemovela_SetRetentionState_FullMethodName      = "/mnemovela.v1.Mnemovela/SetRetentionState"
	Mnemovela_VerifyCommitIndex_FullMethodName      = "/mnemovela.v1.Mnemovela/VerifyCommitIndex"
	Mnemovela_Admit_FullMethodName                  = "/mnemovela.v1.Mnemovela/Admit"
	Mnemovela_Revise_FullMethodName                 = "/mnemovela.v1.Mnemovela/Revise"
	Mnemovela_DeleteCommit_FullMethodName           = "/mnemovela.v1.Mnemovela/DeleteCommit"
	Mnemovela_DispositionEvidence_FullMethodName    = "/mnemovela.v1.Mnemovela/DispositionEvidence"
	Mnemovela_SetLegalHold_FullMethodName           = "/mnemovela.v1.Mnemovela/SetLegalHold"
	Mnemovela_IsLegalHold_FullMethodName            = "/mnemovela.v1.Mnemovela/IsLegalHold"
	Mnemovela_ExecuteDisposal_FullMethodName        = "/mnemovela.v1.Mnemovela/ExecuteDisposal"
)

// MnemovelaClient is the client API for Mnemovela service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MnemovelaClient interface {
	// --- typed writes ---
	CommitMemory(ctx context.Context, in *CommitMemoryRequest, opts ...grpc.CallOption) (*CommitMemoryResponse, error)
	AddEpisode(ctx context.Context, in *AddEpisodeRequest, opts ...grpc.CallOption) (*AddEpisodeResponse, error)
	AddFact(ctx context.Context, in *AddFactRequest, opts ...grpc.CallOption) (*AddFactResponse, error)
	InvalidateFact(ctx context.Context, in *InvalidateFactRequest, opts ...grpc.CallOption) (*InvalidateFactResponse, error)
	UpsertSubject(ctx context.Context, in *UpsertSubjectRequest, opts ...grpc.CallOption) (*UpsertSubjectResponse, error)
	UpsertEntity(ctx context.Context, in *UpsertEntityRequest, opts ...grpc.CallOption) (*UpsertEntityResponse, error)
	// --- queries ---
	SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error)
	QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error)
	QueryFacts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error)
	// --- resolution ---
	ResolveEntity(ctx context.Context, in *ResolveEntityRequest, opts ...grpc.CallOption) (*ResolveEntityResponse, error)
	ResolveEntityExplained(ctx context.Context, in *ResolveEntityExplainedRequest, opts ...grpc.CallOption) (*ResolveEntityExplainedResponse, error)
	// --- extraction ---
	ExtractEpisode(ctx context.Context, in *ExtractEpisodeRequest, opts ...grpc.CallOption) (*ExtractEpisodeResponse, error)
	// --- branching ---
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error)
	// --- maintenance ---
	SetRetentionState(ctx context.Context, in *SetRetentionStateRequest, opts ...grpc.CallOption) (*SetRetentionStateResponse, error)
	VerifyCommitIndex(ctx context.Context, in *VerifyCommitIndexRequest, opts ...grpc.CallOption) (*VerifyCommitIndexResponse, error)
	// --- admission & revision ---
	Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error)
	Revise(ctx context.Context, in *ReviseRequest, opts ...grpc.CallOption) (*ReviseResponse, error)
	// DeleteCommit physically deletes a commit and its derived chain, returning
	// disposition evidence.
	DeleteCommit(ctx context.Context, in *DeleteCommitRequest, opts ...grpc.CallOption) (*DeleteCommitResponse, error)
	// DispositionEvidence returns the recorded disposition evidence for a commit.
	DispositionEvidence(ctx context.Context, in *DispositionEvidenceRequest, opts ...grpc.CallOption) (*DispositionEvidenceResponse, error)
	// SetLegalHold marks or unmarks a commit as excluded from disposal.
	SetLegalHold(ctx context.Context, in *SetLegalHoldRequest, opts ...grpc.CallOption) (*SetLegalHoldResponse, error)
	// IsLegalHold reports whether a commit is under legal hold.
	IsLegalHold(ctx context.Context, in *IsLegalHoldRequest, opts ...grpc.CallOption) (*IsLegalHoldResponse, error)
	// ExecuteDisposal physically deletes tombstoned commits past their grace
	// period, skipping legal-held commits.
	ExecuteDisposal(ctx context.Context, in *ExecuteDisposalRequest, opts ...grpc.CallOption) (*ExecuteDisposalResponse, error)
}

type mnemovelaClient struct {
	cc grpc.ClientConnInterface
}

func NewMnemovelaClient(cc grpc.ClientConnInterface) MnemovelaClient {
	return &mnemovelaClient{cc}
}

func (c *mnemovelaClient) CommitMemory(ctx context.Context, in *CommitMemoryRequest, opts ...grpc.CallOption) (*CommitMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMemoryResponse)
	err := c.cc.Invoke(ctx, Mnemovela_CommitMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) AddEpisode(ctx context.Context, in *AddEpisodeRequest, opts ...grpc.CallOption) (*AddEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEpisodeResponse)
	err := c.cc.Invoke(ctx, Mnemovela_AddEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) AddFact(ctx context.Context, in *AddFactRequest, opts ...grpc.CallOption) (*AddFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFactResponse)
	err := c.cc.Invoke(ctx, Mnemovela_AddFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) InvalidateFact(ctx context.Context, in *InvalidateFactRequest, opts ...grpc.CallOption) (*InvalidateFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateFactResponse)
	err := c.cc.Invoke(ctx, Mnemovela_InvalidateFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) UpsertSubject(ctx context.Context, in *UpsertSubjectRequest, opts ...grpc.CallOption) (*UpsertSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSubjectResponse)
	err := c.cc.Invoke(ctx, Mnemovela_UpsertSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) UpsertEntity(ctx context.Context, in *UpsertEntityRequest, opts ...grpc.CallOption) (*UpsertEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEntityResponse)
	err := c.cc.Invoke(ctx, Mnemovela_UpsertEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) SearchMemory(ctx context.Context, in *SearchMemoryRequest, opts ...grpc.CallOption) (*SearchMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMemoryResponse)
	err := c.cc.Invoke(ctx, Mnemovela_SearchMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) QueryMemories(ctx context.Context, in *QueryMemoriesRequest, opts ...grpc.CallOption) (*QueryMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMemoriesResponse)
	err := c.cc.Invoke(ctx, Mnemovela_QueryMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) QueryFacts(ctx context.Context, in *QueryFactsRequest, opts ...grpc.CallOption) (*QueryFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFactsResponse)
	err := c.cc.Invoke(ctx, Mnemovela_QueryFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) ResolveEntity(ctx context.Context, in *ResolveEntityRequest, opts ...grpc.CallOption) (*ResolveEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEntityResponse)
	err := c.cc.Invoke(ctx, Mnemovela_ResolveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) ResolveEntityExplained(ctx context.Context, in *ResolveEntityExplainedRequest, opts ...grpc.CallOption) (*ResolveEntityExplainedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEntityExplainedResponse)
	err := c.cc.Invoke(ctx, Mnemovela_ResolveEntityExplained_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) ExtractEpisode(ctx context.Context, in *ExtractEpisodeRequest, opts ...grpc.CallOption) (*ExtractEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractEpisodeResponse)
	err := c.cc.Invoke(ctx, Mnemovela_ExtractEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, Mnemovela_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeBranchResponse)
	err := c.cc.Invoke(ctx, Mnemovela_MergeBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, Mnemovela_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) SetRetentionState(ctx context.Context, in *SetRetentionStateRequest, opts ...grpc.CallOption) (*SetRetentionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRetentionStateResponse)
	err := c.cc.Invoke(ctx, Mnemovela_SetRetentionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) VerifyCommitIndex(ctx context.Context, in *VerifyCommitIndexRequest, opts ...grpc.CallOption) (*VerifyCommitIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCommitIndexResponse)
	err := c.cc.Invoke(ctx, Mnemovela_VerifyCommitIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitResponse)
	err := c.cc.Invoke(ctx, Mnemovela_Admit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) Revise(ctx context.Context, in *ReviseRequest, opts ...grpc.CallOption) (*ReviseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviseResponse)
	err := c.cc.Invoke(ctx, Mnemovela_Revise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) DeleteCommit(ctx context.Context, in *DeleteCommitRequest, opts ...grpc.CallOption) (*DeleteCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommitResponse)
	err := c.cc.Invoke(ctx, Mnemovela_DeleteCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) DispositionEvidence(ctx context.Context, in *DispositionEvidenceRequest, opts ...grpc.CallOption) (*DispositionEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispositionEvidenceResponse)
	err := c.cc.Invoke(ctx, Mnemovela_DispositionEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) SetLegalHold(ctx context.Context, in *SetLegalHoldRequest, opts ...grpc.CallOption) (*SetLegalHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLegalHoldResponse)
	err := c.cc.Invoke(ctx, Mnemovela_SetLegalHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) IsLegalHold(ctx context.Context, in *IsLegalHoldRequest, opts ...grpc.CallOption) (*IsLegalHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsLegalHoldResponse)
	err := c.cc.Invoke(ctx, Mnemovela_IsLegalHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnemovelaClient) ExecuteDisposal(ctx context.Context, in *ExecuteDisposalRequest, opts ...grpc.CallOption) (*ExecuteDisposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteDisposalResponse)
	err := c.cc.Invoke(ctx, Mnemovela_ExecuteDisposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MnemovelaServer is the server API for Mnemovela service.
// All implementations must embed UnimplementedMnemovelaServer
// for forward compatibility.
type MnemovelaServer interface {
	// --- typed writes ---
	CommitMemory(context.Context, *CommitMemoryRequest) (*CommitMemoryResponse, error)
	AddEpisode(context.Context, *AddEpisodeRequest) (*AddEpisodeResponse, error)
	AddFact(context.Context, *AddFactRequest) (*AddFactResponse, error)
	InvalidateFact(context.Context, *InvalidateFactRequest) (*InvalidateFactResponse, error)
	UpsertSubject(context.Context, *UpsertSubjectRequest) (*UpsertSubjectResponse, error)
	UpsertEntity(context.Context, *UpsertEntityRequest) (*UpsertEntityResponse, error)
	// --- queries ---
	SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error)
	QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error)
	QueryFacts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error)
	// --- resolution ---
	ResolveEntity(context.Context, *ResolveEntityRequest) (*ResolveEntityResponse, error)
	ResolveEntityExplained(context.Context, *ResolveEntityExplainedRequest) (*ResolveEntityExplainedResponse, error)
	// --- extraction ---
	ExtractEpisode(context.Context, *ExtractEpisodeRequest) (*ExtractEpisodeResponse, error)
	// --- branching ---
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error)
	// --- maintenance ---
	SetRetentionState(context.Context, *SetRetentionStateRequest) (*SetRetentionStateResponse, error)
	VerifyCommitIndex(context.Context, *VerifyCommitIndexRequest) (*VerifyCommitIndexResponse, error)
	// --- admission & revision ---
	Admit(context.Context, *AdmitRequest) (*AdmitResponse, error)
	Revise(context.Context, *ReviseRequest) (*ReviseResponse, error)
	// DeleteCommit physically deletes a commit and its derived chain, returning
	// disposition evidence.
	DeleteCommit(context.Context, *DeleteCommitRequest) (*DeleteCommitResponse, error)
	// DispositionEvidence returns the recorded disposition evidence for a commit.
	DispositionEvidence(context.Context, *DispositionEvidenceRequest) (*DispositionEvidenceResponse, error)
	// SetLegalHold marks or unmarks a commit as excluded from disposal.
	SetLegalHold(context.Context, *SetLegalHoldRequest) (*SetLegalHoldResponse, error)
	// IsLegalHold reports whether a commit is under legal hold.
	IsLegalHold(context.Context, *IsLegalHoldRequest) (*IsLegalHoldResponse, error)
	// ExecuteDisposal physically deletes tombstoned commits past their grace
	// period, skipping legal-held commits.
	ExecuteDisposal(context.Context, *ExecuteDisposalRequest) (*ExecuteDisposalResponse, error)
	mustEmbedUnimplementedMnemovelaServer()
}

// UnimplementedMnemovelaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMnemovelaServer struct{}

func (UnimplementedMnemovelaServer) CommitMemory(context.Context, *CommitMemoryRequest) (*CommitMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitMemory not implemented")
}
func (UnimplementedMnemovelaServer) AddEpisode(context.Context, *AddEpisodeRequest) (*AddEpisodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEpisode not implemented")
}
func (UnimplementedMnemovelaServer) AddFact(context.Context, *AddFactRequest) (*AddFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFact not implemented")
}
func (UnimplementedMnemovelaServer) InvalidateFact(context.Context, *InvalidateFactRequest) (*InvalidateFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateFact not implemented")
}
func (UnimplementedMnemovelaServer) UpsertSubject(context.Context, *UpsertSubjectRequest) (*UpsertSubjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSubject not implemented")
}
func (UnimplementedMnemovelaServer) UpsertEntity(context.Context, *UpsertEntityRequest) (*UpsertEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEntity not implemented")
}
func (UnimplementedMnemovelaServer) SearchMemory(context.Context, *SearchMemoryRequest) (*SearchMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMemory not implemented")
}
func (UnimplementedMnemovelaServer) QueryMemories(context.Context, *QueryMemoriesRequest) (*QueryMemoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMemories not implemented")
}
func (UnimplementedMnemovelaServer) QueryFacts(context.Context, *QueryFactsRequest) (*QueryFactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFacts not implemented")
}
func (UnimplementedMnemovelaServer) ResolveEntity(context.Context, *ResolveEntityRequest) (*ResolveEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveEntity not implemented")
}
func (UnimplementedMnemovelaServer) ResolveEntityExplained(context.Context, *ResolveEntityExplainedRequest) (*ResolveEntityExplainedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveEntityExplained not implemented")
}
func (UnimplementedMnemovelaServer) ExtractEpisode(context.Context, *ExtractEpisodeRequest) (*ExtractEpisodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractEpisode not implemented")
}
func (UnimplementedMnemovelaServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedMnemovelaServer) MergeBranch(context.Context, *MergeBranchRequest) (*MergeBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeBranch not implemented")
}
func (UnimplementedMnemovelaServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedMnemovelaServer) SetRetentionState(context.Context, *SetRetentionStateRequest) (*SetRetentionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRetentionState not implemented")
}
func (UnimplementedMnemovelaServer) VerifyCommitIndex(context.Context, *VerifyCommitIndexRequest) (*VerifyCommitIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCommitIndex not implemented")
}
func (UnimplementedMnemovelaServer) Admit(context.Context, *AdmitRequest) (*AdmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admit not implemented")
}
func (UnimplementedMnemovelaServer) Revise(context.Context, *ReviseRequest) (*ReviseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revise not implemented")
}
func (UnimplementedMnemovelaServer) DeleteCommit(context.Context, *DeleteCommitRequest) (*DeleteCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCommit not implemented")
}
func (UnimplementedMnemovelaServer) DispositionEvidence(context.Context, *DispositionEvidenceRequest) (*DispositionEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispositionEvidence not implemented")
}
func (UnimplementedMnemovelaServer) SetLegalHold(context.Context, *SetLegalHoldRequest) (*SetLegalHoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLegalHold not implemented")
}
func (UnimplementedMnemovelaServer) IsLegalHold(context.Context, *IsLegalHoldRequest) (*IsLegalHoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLegalHold not implemented")
}
func (UnimplementedMnemovelaServer) ExecuteDisposal(context.Context, *ExecuteDisposalRequest) (*ExecuteDisposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDisposal not implemented")
}
func (UnimplementedMnemovelaServer) mustEmbedUnimplementedMnemovelaServer() {}
func (UnimplementedMnemovelaServer) testEmbeddedByValue()                   {}

// UnsafeMnemovelaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MnemovelaServer will
// result in compilation errors.
type UnsafeMnemovelaServer interface {
	mustEmbedUnimplementedMnemovelaServer()
}

func RegisterMnemovelaServer(s grpc.ServiceRegistrar, srv MnemovelaServer) {
	// If the following call pancis, it indicates UnimplementedMnemovelaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mnemovela_ServiceDesc, srv)
}

func _Mnemovela_CommitMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).CommitMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_CommitMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).CommitMemory(ctx, req.(*CommitMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_AddEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).AddEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_AddEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).AddEpisode(ctx, req.(*AddEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_AddFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).AddFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_AddFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).AddFact(ctx, req.(*AddFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_InvalidateFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).InvalidateFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_InvalidateFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).InvalidateFact(ctx, req.(*InvalidateFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_UpsertSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).UpsertSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_UpsertSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).UpsertSubject(ctx, req.(*UpsertSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_UpsertEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).UpsertEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_UpsertEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).UpsertEntity(ctx, req.(*UpsertEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_SearchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).SearchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_SearchMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).SearchMemory(ctx, req.(*SearchMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_QueryMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).QueryMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_QueryMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).QueryMemories(ctx, req.(*QueryMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_QueryFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).QueryFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_QueryFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).QueryFacts(ctx, req.(*QueryFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_ResolveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).ResolveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_ResolveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).ResolveEntity(ctx, req.(*ResolveEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_ResolveEntityExplained_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEntityExplainedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).ResolveEntityExplained(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_ResolveEntityExplained_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).ResolveEntityExplained(ctx, req.(*ResolveEntityExplainedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_ExtractEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).ExtractEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_ExtractEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).ExtractEpisode(ctx, req.(*ExtractEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_MergeBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).MergeBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_MergeBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).MergeBranch(ctx, req.(*MergeBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_SetRetentionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRetentionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).SetRetentionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_SetRetentionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).SetRetentionState(ctx, req.(*SetRetentionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_VerifyCommitIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCommitIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).VerifyCommitIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_VerifyCommitIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).VerifyCommitIndex(ctx, req.(*VerifyCommitIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_Admit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).Admit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_Admit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).Admit(ctx, req.(*AdmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_Revise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).Revise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_Revise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).Revise(ctx, req.(*ReviseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_DeleteCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).DeleteCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_DeleteCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).DeleteCommit(ctx, req.(*DeleteCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_DispositionEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispositionEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).DispositionEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_DispositionEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).DispositionEvidence(ctx, req.(*DispositionEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_SetLegalHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLegalHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).SetLegalHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_SetLegalHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).SetLegalHold(ctx, req.(*SetLegalHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_IsLegalHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLegalHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).IsLegalHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_IsLegalHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).IsLegalHold(ctx, req.(*IsLegalHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mnemovela_ExecuteDisposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDisposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnemovelaServer).ExecuteDisposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mnemovela_ExecuteDisposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnemovelaServer).ExecuteDisposal(ctx, req.(*ExecuteDisposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mnemovela_ServiceDesc is the grpc.ServiceDesc for Mnemovela service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mnemovela_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mnemovela.v1.Mnemovela",
	HandlerType: (*MnemovelaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitMemory",
			Handler:    _Mnemovela_CommitMemory_Handler,
		},
		{
			MethodName: "AddEpisode",
			Handler:    _Mnemovela_AddEpisode_Handler,
		},
		{
			MethodName: "AddFact",
			Handler:    _Mnemovela_AddFact_Handler,
		},
		{
			MethodName: "InvalidateFact",
			Handler:    _Mnemovela_InvalidateFact_Handler,
		},
		{
			MethodName: "UpsertSubject",
			Handler:    _Mnemovela_UpsertSubject_Handler,
		},
		{
			MethodName: "UpsertEntity",
			Handler:    _Mnemovela_UpsertEntity_Handler,
		},
		{
			MethodName: "SearchMemory",
			Handler:    _Mnemovela_SearchMemory_Handler,
		},
		{
			MethodName: "QueryMemories",
			Handler:    _Mnemovela_QueryMemories_Handler,
		},
		{
			MethodName: "QueryFacts",
			Handler:    _Mnemovela_QueryFacts_Handler,
		},
		{
			MethodName: "ResolveEntity",
			Handler:    _Mnemovela_ResolveEntity_Handler,
		},
		{
			MethodName: "ResolveEntityExplained",
			Handler:    _Mnemovela_ResolveEntityExplained_Handler,
		},
		{
			MethodName: "ExtractEpisode",
			Handler:    _Mnemovela_ExtractEpisode_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _Mnemovela_CreateBranch_Handler,
		},
		{
			MethodName: "MergeBranch",
			Handler:    _Mnemovela_MergeBranch_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _Mnemovela_ListBranches_Handler,
		},
		{
			MethodName: "SetRetentionState",
			Handler:    _Mnemovela_SetRetentionState_Handler,
		},
		{
			MethodName: "VerifyCommitIndex",
			Handler:    _Mnemovela_VerifyCommitIndex_Handler,
		},
		{
			MethodName: "Admit",
			Handler:    _Mnemovela_Admit_Handler,
		},
		{
			MethodName: "Revise",
			Handler:    _Mnemovela_Revise_Handler,
		},
		{
			MethodName: "DeleteCommit",
			Handler:    _Mnemovela_DeleteCommit_Handler,
		},
		{
			MethodName: "DispositionEvidence",
			Handler:    _Mnemovela_DispositionEvidence_Handler,
		},
		{
			MethodName: "SetLegalHold",
			Handler:    _Mnemovela_SetLegalHold_Handler,
		},
		{
			MethodName: "IsLegalHold",
			Handler:    _Mnemovela_IsLegalHold_Handler,
		},
		{
			MethodName: "ExecuteDisposal",
			Handler:    _Mnemovela_ExecuteDisposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mnemovela_v1.proto",
}
